define({ root:
//begin v1.x content
({
	information: "Information",
	warning: "Warning",
	error: "Error",
	confirmation: "Confirmation",
	progress: "Progress",
	loading: "Loading",
	close: "Close",
	idxErrorDialog_detailTabLabel: "Fix This Problem",
	idxErrorDialog_moreTabLabel: "Get More Help"
})
//end v1.x content
,
"zh": true,
"zh-tw": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true, "id": true,
"it": true,
"hu": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"ar": true,
"bg": true,
"he": true,
"hr": true,
"uk": true,"vi":true,
"bs": true,
"mk": true,
"sr": true
});
