define({root:
//begin v1.x content
({
	FlipCardContainerTitle: "Pluggable UI",
	DefaultPageContent: "Pluggable UI Default Page Content",
	noSuchPage: "no Such Page!",
	settingsPage: "It's a Settings Page!",
	savedSuccessfully: "Saved Successfully!",
	loadedSuccessfully: "Loaded Successfully!",
	savedLayoutCleared: "Saved Layout Cleared!"
})
,
"zh": true,
"zh-tw": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true, "id": true,
"it": true,
"hu": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"ar": true,
"bg": true,
"he": true,
"hr": true,
"uk": true,"vi":true,
"bs": true,
"mk": true,
"sr": true
});

