define({root:
//begin v1.x content
({
	statusIssueMessage: "Item is not in the Original Normal Status",
	
	defaultActionTitle: "Default Action",
	flipToDetailActionTitle: "Click to Flip To Detail",
	flipToMainActionTitle: "Click to Flip Back To Main",
	settingsActionTitle: "Click to Show Detail Settings",
	settingsDetailActionTitle: "Click to Show Main Settings",
	maxActionTitle: "Click to Maximum",
	minActionTitle: "Click to Minimum",
	stackActionTitle: "Click to Hide",
	closeActionTitle: "Close",
	gridMaximumStatus: "Grid is already in maximum status",
	stackCardNotify: "Card Item"
})
,
"zh": true,
"zh-tw": true,
"tr": true,
"th": true,
"sv": true,
"sl": true,
"sk": true,
"ru": true,
"ro": true,
"pt": true,
"pt-pt": true,
"pl": true,
"nl": true,
"nb": true,
"ko": true,
"kk": true,
"ja": true, "id": true,
"it": true,
"hu": true,
"fr": true,
"fi": true,
"es": true,
"el": true,
"de": true,
"da": true,
"cs": true,
"ca": true,
"ar": true,
"bg": true,
"he": true,
"hr": true,
"uk": true,"vi":true,
"bs": true,
"mk": true,
"sr": true
});

