define({     
//begin v1.x content
	closeLabel: "Zatvori",
	configureLabel: "Konfiguriši",
	editLabel: "Uredi",
	filterLabel: "Filtriraj",
	clearFilterLabel: "Obriši",
	helpLabel: "Pomoć",
	infoLabel: "Informacije",
	minimizeLabel: "Umanji",
	maximizeLabel: "Uvećaj",
	printLabel: "Odštampaj",
	refreshLabel: "Osveži",
	restoreLabel: "Vrati",
	nextPageLabel: "Sledeće",
	previousPageLabel: "Prethodno",
	lastPageLabel: "Poslednje",
	firstPageLabel: "Prvo",
	closeTip: "Zatvori",
	configureTip: "Konfiguriši",
	editTip: "Uredi",
	filterTip: "Filtriraj",
	clearFilterTip: "Obriši filter",
	helpTip: "Zatraži pomoć",
	infoTip: "Zatraži informacije",
	minimizeTip: "Umanji",
	maximizeTip: "Uvećaj",
	printTip: "Odštampaj",
	refreshTip: "Osveži",
	restoreTip: "Vrati",
	nextPageTip: "Sledeća stranica",
	previousPageTip: "Prethodna stranica",
	lastPageTip: "Poslednja stranica",
	firstPageTip: "Prva stranica"
//end v1.x content
});

