define({     
//begin v1.x content
	closeLabel: "Жабу",
	configureLabel: "Теңшеу",
	editLabel: "Өңдеу",
	filterLabel: "Сүзгі",
	clearFilterLabel: "Тазалау",
	helpLabel: "Анықтама",
	infoLabel: "Ақпарат",
	minimizeLabel: "Кішірейту",
	maximizeLabel: "Ұлғайту",
	printLabel: "Басып шығару",
	refreshLabel: "Жаңарту",
	restoreLabel: "Қалпына келтіру",
	nextPageLabel: "Келесі",
	previousPageLabel: "Алдыңғы",
	lastPageLabel: "Соңғы",
	firstPageLabel: "Бірінші",
	closeTip: "Жабу",
	configureTip: "Теңшеу",
	editTip: "Өңдеу",
	filterTip: "Сүзгі",
	clearFilterTip: "Сүзгіні тазалау",
	helpTip: "Анықтама алу",
	infoTip: "Ақпарат алу",
	minimizeTip: "Кішірейту",
	maximizeTip: "Ұлғайту",
	printTip: "Басып шығару",
	refreshTip: "Жаңарту",
	restoreTip: "Қалпына келтіру",
	nextPageTip: "Келесі бет",
	previousPageTip: "Алдыңғы бет",
	lastPageTip: "Соңғы бет",
	firstPageTip: "Бірінші бет"
//end v1.x content
});

